#+TITLE: Final Exam Problem Bank
* Total [36/50]

* General [7/7]
** Sakurai [4/4]
** Likharev [3/3]
*** 4.4: Power of Sigma Matrices
Problem 4.4. Calculate the following expressions,

(i) $(\mathbf{c} \cdot \boldsymbol{\sigma})^n$, and then

(ii) $(b \mathrm{I}+\mathbf{c} \cdot \boldsymbol{\sigma})^n$, for the scalar product
$\mathbf{c} \cdot \boldsymbol{\sigma}$ of the Pauli matrix vector $\boldsymbol{\sigma} \equiv
\mathbf{n}_x \boldsymbol{\sigma}_x+\mathbf{n}_y \sigma_y+\mathbf{n}_z \boldsymbol{\sigma}_z$ by
an arbitrary $c$ -number vector $\mathbf{c}$, where $n \geqslant 0$ is an integer, and
$b$ is an arbitrary scalar $c$ number. (Change this to bI + i |c| \sigma, to use
exponential form)

Hint: For task (ii), you may like to use
the binomial theorem2, and then transform the result in a way enabling you to
use the same theorem backwards.

*** 4.19: Eigenvalue and Measurement
Problem 4.19. In a certain basis, the Hamiltonian of a two-level system is
described by the matrix $$ \mathrm{H}=\left(\begin{array}{cc} E_1 & 0 \\ 0 & E_2
\end{array}\right), \quad \text { with } E_1 \neq E_2, $$ while the operator of
some observable $A$ of this system, by the matrix $$
\mathrm{A}=\left(\begin{array}{ll} 1 & 1 \\ 1 & 1 \end{array}\right) $$

For the system's state with the energy definitely equal to $E_1$, find the
possible results of measurements of the observable $A$ and the probabilities of
the corresponding measurement outcomes.

*** 4.23: Anticommutation and Eigenvalue
A certain state $\gamma$ is an eigenstate of each of two operators
$\hat{A}$ and $\hat{B}$. What can be said about the corresponding eigenvalues
$a$ and $b$, if the operators anticommute?

* Atomic Physics [12/12]
** Sakurai [5/5]
*** 2.10: Time Evolution
Let $\left|a^{\prime}\right\rangle$ and $\left|a^{\prime
\prime}\right\rangle$ be eigenstates of a Hermitian operator $A$ with
eigenvalues $a^{\prime}$ and $a^{\prime \prime}$, respectively $\left(a^{\prime}
\neq a^{\prime \prime}\right)$. The Hamiltonian operator is given by $$
H=\left|a^{\prime}\right\rangle \delta\left\langle a^{\prime \prime}|+|
a^{\prime \prime}\right\rangle \delta\left\langle a^{\prime}\right| $$ where
$\delta$ is just a real number.
a. Clearly, $\left|a^{\prime}\right\rangle$ and $\left|a^{\prime
   \prime}\right\rangle$ are not eigenstates of the Hamiltonian. Write down the
   eigenstates of the Hamiltonian. What are their energy eigenvalues?
b. Suppose the system is known to be in state $\left|a^{\prime}\right\rangle$ at
   $t=0$. Write down the state vector in the Schrödinger picture for $t>0$.
c. What is the probability for finding the system in $\left|a^{\prime
   \prime}\right\rangle$ for $t>0$ if the system is known to be in state
   $\left|a^{\prime}\right\rangle$ at $t=0$ ?
d. Can you think of a physical situation corresponding to this problem?
*** 2.23: Operator Algebra
Make the definitions $$ J_{ \pm} \equiv h a_{ \pm}^{\dagger} a_{\mp}, \quad J_z
\equiv \frac{\bar{h}}{2}\left(a_{+}^{\dagger} a_{+}-a_{-}^{\dagger}
a_{-}\right), \quad N \equiv a_{+}^{\dagger} a_{+}+a_{-}^{\dagger} a_{-} $$
where $a_{ \pm}$and $a_{ \pm}^{\dagger}$ are the annihilation and creation
operators of two independent simple harmonic oscillators satisfying the usual
simple harmonic oscillator commutation relations. Also make the definition $$
\mathbf{J}^2 \equiv J_z^2+\frac{1}{2}\left(J_{+} J_{-}+J_{-} J_{+}\right) . $$

Prove $$ \left[J_z, J_{ \pm}\right]= \pm \bar{h} J_{ \pm},
\quad\left[\mathbf{J}^2, J_z\right]=0, \quad
\mathbf{J}^2=\left(\frac{\bar{h}^2}{2}\right)
N\left[\left(\frac{N}{2}\right)+1\right] $$
***
*** 3.23: Angular Momentum Operator
The wave function of a particle subjected to a spherically symmetrical
potential $V(r)$ is given by $$ \psi(\mathbf{x})=(x+y+3 z) f(r) . $$
a. Is $\psi$ an eigenfunction of $\mathbf{L}^2$ ? If so, what is the $l$-value?
   If not, what are the possible values of $l$ we may obtain when $\mathbf{L}^2$
   is measured?
b. What are the probabilities for the particle to be found in various $m_l$
   states?
c. Suppose it is known somehow that $\psi(\mathbf{x})$ is an energy
   eigenfunction with eigenvalue $E$. Indicate how we may find $V(r)$.
*** 5.1: Simple Perturbation Theory
A simple harmonic oscillator (in one dimension) is subjected to a perturbation
$$
H_1=b x
$$
where $b$ is a real constant.
a. Calculate the energy shift of the ground state to lowest nonvanishing order.
b. Solve this problem exactly and compare with your result obtained in (a).
*** 5.7: Simple Harmonic Oscillator and Perturbation Theory (a&b only)
Consider an isotropic harmonic oscillator in two dimensions. The Hamiltonian is
$$ H_0=\frac{p_x^2}{2 m}+\frac{p_y^2}{2 m}+\frac{m
\omega^2}{2}\left(x^2+y^2\right) . $$
a. What are the energies of the three lowest-lying states? Is there any
   degeneracy?
b. We now apply a perturbation
$$ V=\delta m \omega^2 x y $$ where $\delta$ is a dimensionless real number much
smaller than unity. Find the zerothorder energy eigenket and the corresponding
energy to first order [that is, the unperturbed energy obtained in (a) plus the
first-order energy shift] for each of the three lowest-lying states.
***
** Likharev [4/4]
*** 2.1: Momentum Operator
Problem 2.1. The initial wave packet of a free 1D particle is described by Eq. (2.20) of the lecture notes:
$$
\Psi(x, 0)=\int a_k e^{i k x} d k
$$

(i) Obtain a compact expression for the expectation value $\langle p\rangle$ of the
particle's momentum. Does $\langle p\rangle$ depend on time?

(ii) Calculate $\langle p\rangle$ for the case when the function $\left|a_k\right|^2$ is
symmetric with respect to some value $k_0$.

*** 5.2: Ladder Operator and Heisenberg Picture
Problem 5.2. A spin- $1 / 2$ is placed into an external magnetic field, with a
timeindependent orientation, its magnitude $\mathscr{B}(t)$ being an arbitrary
function of time. Find explicit expressions for the Heisenberg operators and the
expectation values of all three Cartesian components of the spin, as functions
of time, in a coordinate system of your choice.

*** 5.9: Fock State and Ladder Operator
Problem 5.9. For a $1 \mathrm{D}$ harmonic oscillator with mass $m$ and
frequency $\omega_0$, calculate:

(i) all matrix elements $\left\langle n\left|\hat{x}^3\right| n^{\prime}\right\rangle$,

and (ii) the diagonal matrix elements $\left\langle n\left|\hat{x}^4\right| n\right\rangle$,
where $n$ and $n^{\prime}$ are arbitrary Fock states.


Note, \(\begin{aligned} \left\langle n^{\prime}|\hat{x}| n\right\rangle &
=\frac{x_0}{\sqrt{2}}\left[n^{1 / 2} \delta_{n^{\prime}, n-1}+(n+1)^{1 / 2} \delta_{n^{\prime},
n+1}\right] \\ & \equiv\left(\frac{\hbar}{2 m \omega_0}\right)^{1 / 2}\left[n^{1 / 2}
\delta_{n^{\prime}, n-1}+(n+1)^{1 / 2} \delta_{n^{\prime}, n+1}\right] \end{aligned}\)

and \( \begin{aligned} \left\langle n^{\prime}|\hat{x}^{2}| n\right\rangle & =
\frac{x_0^2}{2}\left\{[n(n-1)]^{1 / 2} \delta_{n^{\prime}, n-2}\right. \\ &
\left.+[(n+1)(n+2)]^{1 / 2} \delta_{n^{\prime}, n+2}+(2 n+1) \delta_{n^{\prime}, n}\right\} .
\end{aligned}\)

*** 5.23: Ladder Operator and Angular Momentum
In the basis of the common eigenstates of the operators $\hat{L}_z$ and
$\hat{L}^2$, described by kets $|l, m\rangle$:

(i) calculate the matrix elements $\left\langle l, m_1\left|\hat{L}_x\right| l,
m_2\right\rangle$ and $\left\langle l, m_1\left|\hat{L}_x^2\right| l, m_2\right\rangle$;

(ii) spell out your results for the diagonal matrix elements (with $m_1=m_2$ )
and their $y$-axis counterparts;

and (iii) calculate the diagonal matrix elements $\left\langle l, m\left|\hat{L}_x
\hat{L}_y\right| l, m\right\rangle$ and $\left\langle l, m\left|\hat{L}_y \hat{L}_x\right|
l, m\right\rangle$.

** The Quantum Mechanics Solver [3/3]
- which operators commute with \( \vec{\sigma_{b}}\)
*** 6.1: Hyperfine Splitting
Give the degeneracy of the ground state if one neglects the magnetic interaction
between the nucleus and the external electron. We note $$
\left.\left.\left|m_{\mathrm{e}} ; m_{\mathrm{n}}\right\rangle=\mid \text {
electron : } s_{\mathrm{e}}=1 / 2, m_{\mathrm{e}}\right\rangle \otimes \mid
\text { nucleus : } s_{\mathrm{n}}, m_{\mathrm{n}}\right\rangle $$ a basis of
the total spin states (external electron + nucleus).

*** 6.2: Energy Level of Hyperfine Splitting
We now take into account the interaction between the electron magnetic moment
$\mu_{\mathrm{e}}$ and the nuclear magnetic moment $\mu_{\mathrm{n}}$. As in the
hydrogen atom, one can write the corresponding Hamiltonian (restricted to the
spin subspace) as: $$ \hat{H}=\frac{A}{\hbar^2}
\hat{\boldsymbol{S}}_{\mathrm{e}} \cdot \hat{\boldsymbol{S}}_{\mathrm{n}}, $$

where $A$ is a characteristic energy, and where
$\hat{\boldsymbol{S}}_{\mathrm{e}}$ and $\hat{\boldsymbol{S}}_{\mathrm{n}}$ are
the spin operators of the electron and the nucleus, respectively. We want to
find the eigenvalues of this Hamiltonian.

We introduce the operators $\hat{S}_{\mathrm{e}, \pm}=\hat{S}_{\mathrm{e}, x} \pm i
\hat{S}_{\mathrm{e}, y}$ and $\hat{S}_{\mathrm{n}, \pm}=\hat{S}_{\mathrm{n}, x} \pm
i \hat{S}_{\mathrm{n}, y}$.

(a) Show that $$ \hat{H}=\frac{A}{2 \hbar^2}\left(\hat{S}_{\mathrm{e},+}
\hat{S}_{\mathrm{n},-}+\hat{S}_{\mathrm{e},-} \hat{S}_{\mathrm{n},+}+2
\hat{S}_{\mathrm{e}, z} \hat{S}_{\mathrm{n}, z}\right) $$

(b) Show that the two states $$ \left|m_{\mathrm{e}}=1 / 2 ;
m_{\mathrm{n}}=s_{\mathrm{n}}\right\rangle \quad \text { and } \quad\left|m_{\mathrm{e}}=-1 /
2 ; m_{\mathrm{n}}=-s_{\mathrm{n}}\right\rangle $$ are eigenstates of $\hat{H}$, and
give the corresponding eigenvalues.

(c) What is the action of $\hat{H}$ on the state $\left|m_{\mathrm{e}}=1 / 2 ;
m_{\mathrm{n}}\right\rangle$ with $m_{\mathrm{n}} \neq s_{\mathrm{n}}$ ? What is the
action of $\hat{H}$ on the state $\left|m_{\mathrm{e}}=-1 / 2 ;
m_{\mathrm{n}}\right\rangle$ with $m_{\mathrm{n}} \neq-s_{\mathrm{n}}$ ? (d) Deduce from
these results that the eigenvalues of $\hat{H}$ can be calculated by
diagonalizing $2 \times 2$ matrices of the type: $$
\frac{A}{2}\left(\begin{array}{lr} m_{\mathrm{n}} &
\sqrt{s_{\mathrm{n}}\left(s_{\mathrm{n}}+1\right)-m_{\mathrm{n}}\left(m_{\mathrm{n}}+1\right)}
\\ \sqrt{s_{\mathrm{n}}\left(s_{\mathrm{n}}+1\right)-m_{\mathrm{n}}\left(m_{\mathrm{n}}+1\right)}
& -\left(m_{\mathrm{n}}+1\right) \end{array}\right) . $$

*** 7.3.1: Zeeman Effect
The system is placed in a constant uniform magnetic field $\boldsymbol{B}$
directed along the $z$ axis. The additional Zeeman Hamiltonian has the form $$
\hat{H}_{\mathrm{Z}}=\omega_1 \hat{S}_{1 z}+\omega_2 \hat{S}_{2 z} $$ where $\omega_1=-\gamma_1 B$
and $\omega_2=-\gamma_2 B$. 7.3.1 Matrix representation of the Zeeman Hamiltonian

(a) Taking into account the result of question 7.2.2 and setting $\omega=-\gamma B$, write
the action of $\hat{H}_Z$ on the basis states $\left\{\left|\sigma_1,
\sigma_2\right\rangle\right\}$.

(b) Write in terms of $A$ and $\hbar \omega$ the matrix representation of $$
\hat{H}=\hat{H}_{\mathrm{SS}}+\hat{H}_{\mathrm{A}}+\hat{H}_{\mathrm{Z}} $$ in
the basis $\{|S, m\rangle\}$ of the total spin of the two particles.

(c) Give the numerical value of $\hbar \omega$ in $\mathrm{eV}$ for a field $B=1
\mathrm{~T}$. Is it easy experimentally to be in a strong field regime, i.e. $\hbar
\omega \gg A$ ?
* Quantum Information [10/10]
** Bacon Final [4/4]
*** P1
Problem 1: One Qubit! (30 pts) In this problem you have been given a single
qubit which has the wave function given by the ket
$|\psi\rangle=\frac{1}{\sqrt{2}}|0\rangle+\frac{1+i}{2}|1\rangle$.

(a) (4 pts) What is the bra $\langle\psi|$ corresponding to this ket?

(b) (4 pts) Is this wave function normalized? This is, does $\langle\psi \mid \psi\rangle=1$ ?

(c) $(6 \mathrm{pts})$ If you measure this qubit in the computational basis,
$|0\rangle,|1\rangle$, what are the probabilities of these two outcomes?

(d) (6 pts) Suppose we apply the unitary $$ U=\left[\begin{array}{cc} 1 & 0 \\ 0
& \frac{1-i}{\sqrt{2}} \end{array}\right] $$ to the qubit in the wave function
$|\psi\rangle$. What is the new wave function $U|\psi\rangle$ ?

(e) $(6 \mathrm{pts})$ Recall that the Hadamard matrix is $$
H=\left[\begin{array}{cc} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}
\\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \end{array}\right] $$

If we first apply $U$ from part (d) followed by the Hadamard matrix, this is the
same as applying the unitary $H U$. What is the two by two matrix $H U$ ? (f) (4
pts) Suppose we start with one qubit which has the wave function $|\psi\rangle$. Next we
apply $U$ from part (d). Then we apply the Hadamard $H$. What is the final qubit
wave function? That is, what is $H U|\psi\rangle$ ?

*** P2
Problem 2: Two Qubits! (40 pts)
In this problem we have been given two qubits with the wave function $|\phi\rangle=\frac{1}{2}|01\rangle+\frac{\sqrt{3}}{2}|10\rangle$.
(a) (3 pts) What is the bra $\langle\phi|$ ?
(b) (4 pts) If we measure $|\phi\rangle$ in the computational basis for two qubits, what are the probabilities of the four outcomes, $|00\rangle,|01\rangle,|10\rangle$, and $|11\rangle$ ?
(c) $(5 \mathrm{pts})$ Recall that the single qubit not operator is $X=\left[\begin{array}{ll}0 & 1 \\ 1 & 0\end{array}\right]$ and the single qubit identity operator is $I=$ $\left[\begin{array}{ll}1 & 0 \\ 0 & 1\end{array}\right]$. Write out the two qubit unitary matrix $I \otimes X$ in the computational basis.
(d) (5 pts) Write out the two qubit unitary matrix $X \otimes X$ in the computational basis.
(e) (5 pts) Suppose we apply the unitary matrix $X \otimes X$ to $|\phi\rangle$. What is the resulting two qubit state $(X \otimes X)|\phi\rangle$ ?
(f) (5 pts) Suppose that we feed $|\phi\rangle$ into the following circuit
What is the resulting two qubit wave function?
(g) (3 pts) Return now to $|\phi\rangle$. Suppose we are given two qubits with this wave function and we measure the first of these two qubits in the computational basis, $|0\rangle,|1\rangle$. What are the probabilities of these two outcomes?
(h) (3 pts) Recall that the Bell basis are given by the four two qubit kets
$$
\begin{aligned}
& \left|\Psi_{+}\right\rangle=\frac{1}{\sqrt{2}}(|01\rangle+|10\rangle), \quad\left|\Psi_{-}\right\rangle=\frac{1}{\sqrt{2}}(|01\rangle-|10\rangle), \\
& \left|\Phi_{+}\right\rangle=\frac{1}{\sqrt{2}}(|00\rangle+|11\rangle), \quad\left|\Phi_{-}\right\rangle=\frac{1}{\sqrt{2}}(|00\rangle-|11\rangle) .
\end{aligned}
$$

Suppose that we measure $|\phi\rangle$ in the Bell basis. What are the
probabilities of the four outcomes
$\left|\Phi_{+}\right\rangle,\left|\Phi_{-}\right\rangle,\left|\Psi_{+}\right\rangle$,
and $\left|\Psi_{-}\right\rangle$? (i) (7 pts) Suppose in addition to
$|\phi\rangle$, we have a third qubit whose wave function is
$\frac{1}{\sqrt{2}}(|0\rangle+|1\rangle)$, i.e. we start with $|\phi\rangle
\otimes \frac{1}{\sqrt{2}}(|0\rangle+|1\rangle)$. Suppose you now measure the
first and third qubits of this system in the Bell basis. After this measurement,
the wave function of the second qubit will be separable from the wave function
of the first and the third qubit. Suppose that you got the outcome corresponding
to $\left|\Phi_{+}\right\rangle$: what would the wave function of the second
qubit then be?

*** P3
Problem 3: Outer Products (10 pts)
(a) (3 pts) Let $|+\rangle=\frac{1}{\sqrt{2}}(|0\rangle+|1\rangle)$. Write out the two by two matrix $|+\rangle\langle+|$ in the computational basis, $|0\rangle,|1\rangle$.
(b) (4 pts) Let $|-i\rangle=\frac{1}{\sqrt{2}}(|0\rangle+i|1\rangle)$ and $|+i\rangle=\frac{1}{\sqrt{2}}(|0\rangle-i|1\rangle)$. Suppose that we are given two qubits whose wave function is $\frac{1}{2}|00\rangle+\frac{\sqrt{3}}{2}|11\rangle$. If we measure the first of these qubits in the $|+i\rangle,|-i\rangle$ basis, what are the probabilities of these two outcomes? What is the wave function of these two qubits after the measurement for each of these two possible outcomes?
(c) (3 pts) Define the four dimensional matrix $V=|00\rangle\left\langle 00\left|+e^{\frac{2 \pi i}{3}}\right| 01\right\rangle\langle 01|+\frac{1}{\sqrt{2}}(|10\rangle\langle 10|+i| 11\rangle\langle 10|+i| 10\rangle\langle 11|+| 11\rangle\langle 11|)$. Is this matrix unitary? That is does $V V^{\dagger}=I$ ?

*** P4
Problem 4: n Qubits! (10 pts)
In this problem we will deal with $n$ qubits.
(a) (4 pts) Suppose that we have $n$ qubits which have the wave function $|0\rangle=|0,0, \ldots, 0\rangle$. If we now apply the $n$ qubit Pauli $X$ to these $n$ qubits, $X^{\otimes n}$ (where $X$ is defined Problem 2), what is the resulting $n$ qubit state? Your answer should be a single computational basis state.
(b) (4 pts) Recall the definition of the Hadamard from Problem 1. Suppose we apply the $n$ qubit Hadamard, $H^{\otimes n}$ to $\left(X^{\otimes n}\right)|0\rangle$. ( $H$ is defined in Problem 1.) What is the resulting $n$ qubit wave function? Express it as a sum over computational basis kets, i.e. in the form $\sum_{x=0}^{2^n-1} a_x|x\rangle$, where $a_x$ is some function of $x$ which you must find a formula for.
(c) (2 pts) $H^{\otimes n} X^{\otimes n} H^{\otimes n}$ can be expressed as $A^{\otimes n}$. What is $A$ ?

** MIT P3 [3/3]
*** P1
1. Measurements and uncertainty.
(a) Suppose we prepare a quantum system in an eigenstate $|\psi\rangle$ of some observable $M$, with corresponding eigenvalue $m$. What is the average observed value of $M$, and the standard deviation?
(b) Suppose we have qubit in the state $|0\rangle$, and we measure the observable $X$ (i.e. $\sigma_x$ ). What is the average value of $X$ ? What is the standard deviation of $X$ ?
*** P4
4. Schmidt decompositions. Consider a composite system consisting of two qubits. Find the Schmidt decompositions of the states
$$
\begin{aligned}
\left|\phi_1\right\rangle & =\frac{|00\rangle+|11\rangle+|22\rangle}{\sqrt{3}} \\
\left|\phi_2\right\rangle & =\frac{|00\rangle+|01\rangle+|10\rangle+|11\rangle}{2} \\
\left|\phi_3\right\rangle & =\frac{|00\rangle+|01\rangle+|10\rangle-|11\rangle}{2} \\
\left|\phi_4\right\rangle & =\frac{|00\rangle+|01\rangle+|11\rangle}{\sqrt{3}} .
\end{aligned}
$$
*** P5
5. Interferometers. Consider this single qubit model of an interferometer, where the goal is to estimate an unknown phase $\phi$ :
Let the box with $\phi$ map $|0\rangle \rightarrow|0\rangle$ and $|1\rangle \rightarrow e^{i \phi}|1\rangle$.
(a) Give the states $\left|\psi_1\right\rangle,\left|\psi_2\right\rangle$, and $\left|\psi_3\right\rangle$.
(b) What is the probability $p$ of measuring the final qubit to be one?
(c) If this is experiment is repeated $n$ times, what is the standard deviation $\Delta p$ of the value estimated for $p$ from the measurement results? Also give the uncertainty in the resulting estimate for $\phi$, $\Delta \phi=\Delta p /|d p / d \phi|$.

** MIT P4 [1/1]
*** P1
 Measurement in the Bell basis Show that the circuit performs a measurement in
the basis of the Bell states. Specifically, show that this circuit results in a
measurement being performed with four operators $\left\{M_k\right\}$ such that
$M_k^{\dagger} M_k$ are the four projectors onto the Bell states.


[[file:../Quantum_Information_\[11/11\]/20231127-165019_screenshot.png]]

** MIT MidTerm [2/2]
*** P2
Entanglement distillation by non-projective measurement. Suppose Alice and Bob
share the two-qubit state $\left|\psi_{A
B}\right\rangle=(\sqrt{3}|00\rangle+|11\rangle) / 2$. Recall that a quantum
measurement is specified by a set of operators $\left\{M_0, M_1\right\}$ such
that $\sum_k M_k^{\dagger} M_k=I$. (a) Give $a$ and $b$ such that the quantum
measurement outcome from operator $M_0=a|0\rangle\langle 0|+b| 1\rangle\langle
1|$ acting on $\left|\psi_{A B}\right\rangle$ produces the post-measurement
result $(|00\rangle+|11\rangle) / \sqrt{2}$ with probability $1 / 4$. (15
points) (b) Give an operator $M_1$ such that $M_0^{\dagger} M_0+M_1^{\dagger}
M_1=I$. With what probability does the corresponding outcome occur, acting on
$\left|\psi_{A B}\right\rangle$, and what is the post-measurement result? (10
points)
*** P4
4. Qubit tests. Consider the following three-qubit quantum circuit, in which
   $|\chi\rangle$ and $|\phi\rangle$ are arbitrary qubits:
  [[file:../Quantum_Information_\[11/11\]/20231127-164944_screenshot.png]]

(a) Give the intermediate states of the circuit,
$\left|\psi_0\right\rangle,\left|\psi_1\right\rangle,\left|\psi_2\right\rangle,\left|\psi_3\right\rangle$.
(4 points each)

(b) If the measurement result is zero (ie the top qubit is $|0\rangle$ ), what
is the state of the bottom two qubits? (4 points)

(c) If \(|\langle\chi \mid \phi\rangle|=\alpha\), with what probability is the
measurement result zero? (10 points)




* Condensed Matter Physics [0/14]
- Provided by Prof. Liu

* Sakurai
** Chapter 1
*** 1.2
Prove $$
[A B, C D]=-A C\{D, B\}+A\{C, B\} D-C\{D, A\} B+\{C, A\} D B
$$

*** 1.4
Suppose a $2 \times 2$ matrix $X$ (not necessarily Hermitian, nor unitary) is written as
$$
X=a_0+\sigma \cdot \mathbf{a},
$$
where the matrices $\sigma$ are given in (3.50) and $a_0$ and $a_{1,2,3}$ are numbers.

a. How are $a_0$ and $a_k(k=1,2,3)$ related to $\operatorname{tr}(X)$ and $\operatorname{tr}\left(\sigma_k X\right)$ ?

b. Obtain $a_0$ and $a_k$ in terms of the matrix elements $X_{i j}$.

*** 1.6
Using the rules of bra-ket algebra, prove or evaluate the following:

a. $\operatorname{tr}(X Y)=\operatorname{tr}(Y X)$, where $X$ and $Y$ are operators;

b. $(X Y)^{\dagger}=Y^{\dagger} X^{\dagger}$, where $X$ and $Y$ are operators;

c. $\exp [i f(A)]=$ ? in ket-bra form, where $A$ is a Hermitian operator whose eigenvalues are known;

d. $\sum_{a^{\prime}} \psi_{a^{\prime}}^*\left(\mathbf{x}^{\prime}\right) \psi_{a^{\prime}}\left(\mathbf{x}^{\prime \prime}\right)$, where $\psi_{a^{\prime}}\left(\mathbf{x}^{\prime}\right)=\left\langle\mathbf{x}^{\prime} \mid a^{\prime}\right\rangle$.

*** 1.7
a. Consider two kets $|\alpha\rangle$ and $|\beta\rangle$. Suppose $\left\langle a^{\prime} \mid \alpha\right\rangle,\left\langle a^{\prime \prime} \mid \alpha\right\rangle, \ldots$ and $\left\langle a^{\prime} \mid \beta\right\rangle,\left\langle a^{\prime \prime} \mid \beta\right\rangle, \ldots$ are all known, where $\left|a^{\prime}\right\rangle,\left|a^{\prime \prime}\right\rangle, \ldots$ form a complete set of base kets. Find the matrix representation of the operator $|\alpha\rangle\langle\beta|$ in that basis.
b. We now consider a spin $\frac{1}{2}$ system and let $|\alpha\rangle$ and $|\beta\rangle$ be $\left|S_z ;+\right\rangle$ and $\left|S_x ;+\right\rangle$, respectively. Write down explicitly the square matrix that corresponds to $|\alpha\rangle\langle\beta|$ in the usual ( $s_z$ diagonal) basis.

*** 1.8: Eigenvalue
Suppose $|i\rangle$ and $|j\rangle$ are eigenkets of some Hermitian operator
$A$.

Under what condition can we conclude that $|i\rangle+|j\rangle$ is also an
eigenket of $A$ ? Justify your answer.

*** 1.10
1.10 Using the orthonormality of $|+\rangle$ and $|-\rangle$, prove
$$
\left[S_i, S_j\right]=i \varepsilon_{i j k} \hbar S_k, \quad\left\{S_i, S_j\right\}=\left(\frac{\hbar^2}{2}\right) \delta_{i j},
$$
where
$$
\begin{aligned}
& S_x=\frac{\hbar}{2}(|+\rangle\langle-|+|-\rangle\langle+|), \quad S_y=\frac{i \hbar}{2}(-|+\rangle\langle-|+|-\rangle\langle+|), \\
& S_z=\frac{\hbar}{2}(|+\rangle\langle+|-|-\rangle\langle-|) .
\end{aligned}
$$

*** 1.12: Braket Notation to Matrix
The Hamiltonian operator for a two-state system is given by $$
H=a(|1\rangle\langle 1|-| 2\rangle\langle 2|+| 1\rangle\langle 2|+|
2\rangle\langle 1|), $$ where $a$ is a number with the dimension of energy. Find
the energy eigenvalues and the corresponding energy eigenkets (as linear
combinations of $|1\rangle$ and $|2\rangle$ ).

*** 1.13
A two-state system is characterized by the Hamiltonian
$$
H=H_{11}|1\rangle\left\langle 1\left|+H_{22}\right| 2\right\rangle\langle 2|+H_{12}[|1\rangle\langle 2|+| 2\rangle\langle 1|]
$$
where $H_{11}, H_{22}$, and $H_{12}$ are real numbers with the dimension of energy, and $|1\rangle$ and $|2\rangle$ are eigenkets of some observable $(\neq H)$. Find the energy eigenkets and corresponding energy eigenvalues. Make sure that your answer makes good sense for $H_{12}=0$.
1.14 A spin $\frac{1}{2}$ system is known to be in an eigenstate of $\mathbf{S} \cdot \hat{\mathbf{n}}$ with eigenvalue $\hbar / 2$, where $\hat{\mathbf{n}}$ is a unit vector lying in the $x z$-plane that makes an angle $\gamma$ with the positive $z$-axis.
a. Suppose $S_x$ is measured. What is the probability of getting $+\hbar / 2$ ?
b. Evaluate the dispersion in $S_x$, that is,
$$
\left\langle\left(S_x-\left\langle S_x\right\rangle\right)^2\right\rangle
$$
(For your own peace of mind check your answers for the special cases $\gamma=0, \pi / 2$, and $\pi$.)
*** 1.14
A spin $\frac{1}{2}$ system is known to be in an eigenstate of $\mathbf{S} \cdot \hat{\mathbf{n}}$ with eigenvalue $\hbar / 2$, where $\hat{\mathbf{n}}$ is a unit vector lying in the $x z$-plane that makes an angle $\gamma$ with the positive $z$-axis.
a. Suppose $S_x$ is measured. What is the probability of getting $+\hbar / 2$ ?
b. Evaluate the dispersion in $S_x$, that is,
$$
\left\langle\left(S_x-\left\langle S_x\right\rangle\right)^2\right\rangle
$$
(For your own peace of mind check your answers for the special cases $\gamma=0, \pi / 2$, and $\pi$.)
*** 1.15
A beam of spin $\frac{1}{2}$ atoms goes through a series of Stern-Gerlach type measurements as follows.
a. The first measurement accepts $s_z=\hbar / 2$ atoms and rejects $s_z=-\hbar / 2$ atoms.
b. The second measurement accepts $s_n=\hbar / 2$ atoms and rejects $s_n=-\hbar / 2$ atoms, where $s_n$ is the eigenvalue of the operator $\mathbf{S} \cdot \hat{\mathbf{n}}$, with $\hat{\mathbf{n}}$ making an angle $\beta$ in the $x z$-plane with respect to the $z$-axis.
c. The third measurement accepts $s_z=-\hbar / 2$ atoms and rejects $s_z=\hbar / 2$ atoms.
What is the intensity of the final $s_z=-\hbar / 2$ beam when the $s_z=\hbar / 2$ beam surviving the first measurement is normalized to unity? How must we orient the second measuring apparatus if we are to maximize the intensity of the final $s_z=-\hbar / 2$ beam?
*** 1.18
Two Hermitian operators anticommute:
$$
\{A, B\}=A B+B A=0 .
$$

Is it possible to have a simultaneous (that is, common) eigenket of $A$ and $B$ ? Prove or illustrate your assertion.
*** 1.19
Two observables $A_1$ and $A_2$, which do not involve time explicitly, are known not to commute,
$$
\left[A_1, A_2\right] \neq 0
$$
yet we also know that $A_1$ and $A_2$ both commute with the Hamiltonian:
$$
\left[A_1, H\right]=0, \quad\left[A_2, H\right]=0
$$

Prove that the energy eigenstates are, in general, degenerate. Are there exceptions? As an example, you may think of the central-force problem $H=\mathbf{p}^2 / 2 m+V(r)$, with $A_1 \rightarrow L_z, A_2 \rightarrow L_x$
*** 1.26
a. Prove that $(1 / \sqrt{2})\left(1+i \sigma_x\right)$, where the matrix $\sigma_x$ is given in (3.50), acting on a two-component spinor can be regarded as the matrix representation of the rotation operator about the $x$-axis by angle $-\pi / 2$. (The minus sign signifies that the rotation is clockwise.)

b. Construct the matrix representation of $S_z$ when the eigenkets of $S_y$ are used as base vectors.

*** 1.28
Construct the transformation matrix that connects the $S_z$ diagonal basis to the $S_x$ diagonal basis. Show that your result is consistent with the general relation
$$
U=\sum_r\left|b^{(r)}\right\rangle\left\langle a^{(r)}\right|
$$

** Chapter 2

*** 2.8: Heisenberg Picture
2.8 Consider a free-particle wave packet in one dimension. At $t=0$ it satisfies the minimum uncertainty relation
$$
\left\langle(\Delta x)^2\right\rangle\left\langle(\Delta p)^2\right\rangle=\frac{\bar{h}^2}{4} \quad(t=0) .
$$

In addition, we know
$$
\langle x\rangle=\langle p\rangle=0 \quad(t=0) .
$$

Using the Heisenberg picture, obtain $\left\langle(\Delta x)^2\right\rangle_t$ as a function of $t(t \geq 0)$ when $\left\langle(\Delta x)^2\right\rangle_{t=0}$ is given. (Hint: Take advantage of the property of the minimumuncertainty wave packet you worked out in Chapter 1, Problem 1.20.)
** Chapter 3
*** 3.12: State Representation
a. Consider a pure ensemble of identically prepared spin $\frac{1}{2}$ systems.
   Suppose the expectation values $\left\langle S_x\right\rangle$ and
   $\left\langle S_z\right\rangle$ and the sign of $\left\langle
   S_y\right\rangle$ are known. Show how we may determine the state vector. Why
   is it unnecessary to know the magnitude of $\left\langle S_y\right\rangle$ ?

b. Consider a mixed ensemble of spin $\frac{1}{2}$ systems. Suppose the ensemble
   averages $\left[S_x\right],\left[S_y\right]$, and $\left[S_z\right]$ are all
   known. Show how we may construct the $2 \times 2$ density matrix that
   characterizes the ensemble.

** Chapter 4

** Chapter 5
